name: 'Simple compose service updates'
description: 'Simple compose service update process for your repos'
inputs:
  default_branch: 
    description: 'default branch'
    required: false
    default: 'master'
  prs:
    description: 'prs?'
    required: false
    default: 'generate'
  skips:
    description: 'Skip some services'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: compose service updates
      shell: bash
      run: |
        default_branch=${{ inputs.default_branch }}
        skips=${{ inputs.skips }}
        prs=${{ inputs.prs }}

        # Validate the 'prs' input
        if [[ "$prs" != "generate" && "$prs" != "skip" ]]; then
          echo "Invalid value for 'prs' input. Allowed values are 'generate' or 'skip'."
          exit 1
        fi

        ${{ github.action_path }}/bin/pincher.sh "$default_branch" "$prs" "$skips"